zuul:
  thread-pool:
    thread-pool-key-prefix: zuul
  routes:
    products:
      path: /products/**
      url: https://dummyjson.com/products/
    users:
      path: /users/**
      url: https://dummyjson.com/users/

server:
  port: 8080
